
import { CardData } from '../types';

/* 
 * ======================================================================================
 *  HOW TO ADD NEW CARDS
 * ======================================================================================
 * 
 *  To add a new card to the application, append a new object to the RAW_CARDS array below.
 * 
 *  Format:
 *  { 
 *    name: "Card Name", 
 *    traitValue: "trait-value-from-constants", // e.g., 'chewjitsu', 'halo', 'pizza'
 *    category: "category-name",                // 'head', 'mouth', 'eyes', 'clothes', 'accessories', 'discipline', 'fur'
 *    img: "image-filename.webp" 
 *  }
 * 
 *  Example:
 *  { name: "My New Card", traitValue: "halo", category: "head", img: "my-new-card.webp" },
 * 
 * ======================================================================================
 */

// Data extracted and deduplicated from the provided HTML
const RAW_CARDS = [
  { name: "3D Chess", traitValue: "3dglasses", category: "eyes", img: "3d-chess.webp" },
  { name: "3D Glasses", traitValue: "3dglasses", category: "eyes", img: "3d-glasses.webp" },
  { name: "420 Am", traitValue: "herb", category: "mouth", img: "420-am.webp" },
  { name: "Jaw Breaker", traitValue: "lollipop", category: "mouth", img: "jaw-breaker.webp" },
  { name: "Leash Reverse Polarity", traitValue: "leash", category: "accessories", img: "leash-reverse-polarity.webp" },
  { name: "Special Recipe", traitValue: "pizza", category: "mouth", img: "special-recipe.webp" },
  { name: "Advanced Borg", traitValue: "cyborgeyes", category: "eyes", img: "advanced-borg.webp" },
  { name: "Aftermath", traitValue: "partypopper", category: "mouth", img: "aftermath.webp" },
  { name: "Air Drop", traitValue: "beanie", category: "head", img: "air-drop.webp" },
  { name: "Air Reinforcements", traitValue: "sailor", category: "clothes", img: "air-reinforcements.webp" },
  { name: "Alien Mechanic", traitValue: "overalls", category: "clothes", img: "alien-mechanic.webp" },
  { name: "Amenta", traitValue: "doctor", category: "clothes", img: "amenta.webp" },
  { name: "Anarchy", traitValue: "blackmask", category: "eyes", img: "anarchy.webp" },
  { name: "Ancient Shiba Secrets", traitValue: "red", category: "eyes", img: "ancient-shiba-secrets.webp" },
  { name: "Anonymous Dev", traitValue: "ryoshihead", category: "head", img: "anonymous-dev.webp" },
  { name: "Armored Shib", traitValue: "steelhead", category: "head", img: "armored-shib.webp" },
  { name: "Armored Truck", traitValue: "steelhead", category: "head", img: "armored-truck.webp" },
  { name: "Astroshib", traitValue: "astroclothes", category: "clothes", img: "astroshib.webp" },
  { name: "Avalanche", traitValue: "bluearmor", category: "clothes", img: "avalanche.webp" },
  { name: "I Am Ryoshi", traitValue: "ryoshihead", category: "head", img: "i-am-ryoshi.webp" },
  { name: "Babylon Burn", traitValue: "rasta", category: "head", img: "babylon-burn.webp" },
  { name: "Backstage", traitValue: "rockermakeup", category: "eyes", img: "backstage.webp" },
  { name: "Baffling Blizzard", traitValue: "bluearmor", category: "clothes", img: "baffling-blizzard.webp" },
  { name: "Best Community Ever", traitValue: "smirk", category: "mouth", img: "best-community-ever.webp" },
  { name: "Bling Bling", traitValue: "goldchain", category: "accessories", img: "bling-bling.webp" },
  { name: "Blood Sucker", traitValue: "bathead", category: "head", img: "blood-sucker.webp" },
  { name: "Blow The Wihistle", traitValue: "whistle", category: "mouth", img: "blow-the-whistle.webp" },
  { name: "Bone Breaker", traitValue: "bone", category: "mouth", img: "bone-breaker.webp" },
  { name: "Bonk", traitValue: "blackmask", category: "eyes", img: "bonk.webp" },
  { name: "The General", traitValue: "astroclothes", category: "clothes", img: "the-general.webp" },
  { name: "Bubble Bather", traitValue: "bubblegum", category: "mouth", img: "bubble-bather.webp" },
  { name: "Bubble Burst", traitValue: "pipe", category: "mouth", img: "bubble-burst.webp" },
  { name: "Bubble Flight", traitValue: "bubblegum", category: "mouth", img: "bubble-flight.webp" },
  { name: "Bundled Shib", traitValue: "scarf", category: "clothes", img: "bundled-shib.webp" },
  { name: "Buried Bunker", traitValue: "steelclothes", category: "clothes", img: "buried-bunker.webp" },
  { name: "Bushmaster", traitValue: "memeshades", category: "eyes", img: "bushmaster.webp" },
  { name: "Butterfly On Nose", traitValue: "classiceyes", category: "eyes", img: "butterfly-on-nose.webp" },
  { name: "Call All To Hell", traitValue: "devilhorns", category: "head", img: "call-all-to-hell.webp" },
  { name: "Cannon Fodder", traitValue: "piratepatch", category: "eyes", img: "cannon-fodder.webp" },
  { name: "Cave Hodaven", traitValue: "wizardrobe", category: "clothes", img: "cave-hodaven.webp" },
  { name: "Ceiling Vision", traitValue: "lookup", category: "eyes", img: "ceiling-vision.webp" },
  { name: "Shadowcats Descend", traitValue: "lookup", category: "eyes", img: "shadowcats-descend.webp" },
  { name: "Ceremonial Condolences", traitValue: "dogtags", category: "accessories", img: "ceremonial-condolences.webp" },
  { name: "Certified Organic", traitValue: "herb", category: "mouth", img: "certified-organic.webp" },
  { name: "Championship Ring", traitValue: "jersey", category: "clothes", img: "championship-ring.webp" },
  { name: "Chief Cook", traitValue: "tongueout", category: "mouth", img: "chief-cook.webp" },
  { name: "The Chosen One", traitValue: "crown", category: "head", img: "the-chosen-one.webp" },
  { name: "Chief Of Teresians", traitValue: "crown", category: "head", img: "chief-of-teresians.webp" },
  { name: "Chill Pill", traitValue: "bluehair", category: "head", img: "chill-pill.webp" },
  { name: "Clearvoyance", traitValue: "monocle", category: "eyes", img: "clearvoyance.webp" },
  { name: "Climate Change", traitValue: "peacetank", category: "clothes", img: "climate-change.webp" },
  { name: "Cloud Gazers", traitValue: "lookup", category: "eyes", img: "cloud-gazers.webp" },
  { name: "Clown Car", traitValue: "clownmouth", category: "mouth", img: "clown-car.webp" },
  { name: "Clown In The Closet", traitValue: "clownclothes", category: "clothes", img: "clown-in-the-closet.webp" },
  { name: "Common Cowboy", traitValue: "cowboyhat", category: "head", img: "common-cowboy.webp" },
  { name: "Super Scan", traitValue: "laservisor", category: "eyes", img: "super-scan.webp" },
  { name: "Satellite of Doom", traitValue: "lasereyes", category: "eyes", img: "satellite-of-doom.webp" },
  { name: "Congratulations", traitValue: "pipe", category: "mouth", img: "congratulations.webp" },
  { name: "Fully Decentralized", traitValue: "nofud", category: "clothes", img: "fully-decentralized.webp" },
  { name: "Cooldown", traitValue: "laservisor", category: "eyes", img: "cool-down.webp" },
  { name: "Crown Jewel Heist", traitValue: "crown", category: "head", img: "crown-jewel-heist.webp" },
  { name: "Cuteness Overload", traitValue: "wink", category: "eyes", img: "cutenesss-overload.webp" },
  { name: "Das A Good Boy", traitValue: "noneclothes", category: "clothes", img: "das-a-good-boy.webp" },
  { name: "De Fud Sive", traitValue: "nofud", category: "clothes", img: "de-fud-sive.webp" },
  { name: "Deal With It", traitValue: "memeshades", category: "eyes", img: "deal-with-it.webp" },
  { name: "Decentralization Works", traitValue: "ryoshihead", category: "head", img: "decentralization-works.webp" },
  { name: "Defi Bot", traitValue: "steelclothes", category: "clothes", img: "defi-bot.webp" },
  { name: "Deployment", traitValue: "armyhead", category: "head", img: "deployment.webp" },
  { name: "Designated Driver", traitValue: "partypopper", category: "mouth", img: "designated-driver.webp" },
  { name: "Dev Wooflin", traitValue: "devclothes", category: "clothes", img: "dev-wooflin.webp" },
  { name: "Diamond Paws", traitValue: "goldchain", category: "accessories", img: "diamond-paws.webp" },
  { name: "Dog Pound", traitValue: "beanie", category: "head", img: "dog-pound.webp" },
  { name: "Double Agent Contact", traitValue: "glasses", category: "eyes", img: "double-agent-contact.webp" },
  { name: "Double Vision Venus", traitValue: "crosseyed", category: "eyes", img: "double-vision-venus.webp" },
  { name: "Doxxed", traitValue: "clownmouth", category: "mouth", img: "doxxed.webp" },
  { name: "Drac U Shibe", traitValue: "batclothes", category: "clothes", img: "drac-u-shib.webp" },
  { name: "Drone Strike", traitValue: "cyborghead", category: "head", img: "drone-strike.webp" },
  { name: "Dunkmeister", traitValue: "sportband", category: "head", img: "dunkmeister.webp" },
  { name: "Echolocation", traitValue: "batclothes", category: "clothes", img: "echolocation.webp" },
  { name: "Scorch", traitValue: "flames", category: "mouth", img: "scorch.webp" },
  { name: "Elite Sports Car", traitValue: "goldchain", category: "accessories", img: "elite-sports-car.webp" },
  { name: "Emp", traitValue: "cyborghead", category: "head", img: "emp.webp" },
  { name: "Extra Pair", traitValue: "glasses", category: "eyes", img: "extra-pair.webp" },
  { name: "Falling For Fire", traitValue: "flames", category: "accessories", img: "falling-for-fire.webp" },
  { name: "Fang", traitValue: "bathead", category: "head", img: "fang.webp" },
  { name: "Fetch", traitValue: "tongueout", category: "mouth", img: "fetch.webp" },
  { name: "First Practice", traitValue: "rockervest", category: "accessories", img: "first-practice.webp" },
  { name: "Flirty Fiona", traitValue: "wink", category: "eyes", img: "flirty-fiona.webp" },
  { name: "Shadow Cat Attacks", traitValue: "captainshat", category: "head", img: "shadow-cat-attacks.webp" },
  { name: "For Three", traitValue: "sportband", category: "head", img: "for-three.webp" },
  { name: "Forest Hunters", traitValue: "overalls", category: "clothes", img: "forest-hunters.webp" },
  { name: "Freeze Time", traitValue: "wizardhat", category: "head", img: "freeze-time.webp" },
  { name: "Full Of Fud", traitValue: "crosseyed", category: "eyes", img: "full-of-fud.webp" },
  { name: "Fused Shib", traitValue: "earrings", category: "accessories", img: "fused-shib.webp" },
  { name: "Scaredy Cat", traitValue: "earrings", category: "accessories", img: "scaredy-cat.webp" },
  { name: "The Full Plan", traitValue: "smirk", category: "mouth", img: "the-full-plan.webp" },
  { name: "Galaxy Eyed Ser", traitValue: "spirals", category: "eyes", img: "galaxy-eyed-ser.webp" },
  { name: "Graduation", traitValue: "university", category: "head", img: "graduation.webp" },
  { name: "Rocket Paw Punch", traitValue: "cyborgeyes", category: "eyes", img: "rocket-paw-punch.webp" },
  { name: "Half Time Show", traitValue: "whistle", category: "accessories", img: "half-time-show.webp" },
  { name: "Hall Of Fame Induction", traitValue: "rockermakeup", category: "head", img: "hall-of-fame-induction.webp" },
  { name: "Handfull Of El Bolts", traitValue: "monocle", category: "eyes", img: "handfull-of-el-bolts.webp" },
  { name: "Harness The Sun", traitValue: "blondehair", category: "head", img: "harness-the-sun.webp" },
  { name: "Hats Off", traitValue: "tophat", category: "head", img: "hats-off.webp" },
  { name: "Hermetic Intiate", traitValue: "wizardhat", category: "head", img: "hermetic-initiate.webp" },
  { name: "How Many Licks", traitValue: "lollipop", category: "mouth", img: "how-many-licks.webp" },
  { name: "Hypnotic Tonic", traitValue: "spirals", category: "eyes", img: "hypnotic-tonic.webp" },
  { name: "I Quit", traitValue: "businesssuit", category: "clothes", img: "i-quit.webp" },
  { name: "Shytoshi Half Power", traitValue: "bluehair", category: "head", img: "shytoshi-half-power.webp" },
  { name: "Drill Sergeant", traitValue: "armyhead", category: "head", img: "drill-sergeant.webp" },
  { name: "Fire El", traitValue: "flames", category: "mouth", img: "fire-el.webp" },
  { name: "El Of Water", traitValue: "bluehair", category: "head", img: "el-of-water.webp" },
  { name: "Electrified By El", traitValue: "nonehead", category: "head", img: "electrified-by-el.webp" },
  { name: "Enraged Yek", traitValue: "devilhorns", category: "head", img: "enraged-yek.webp" },
  { name: "Extra Everything", traitValue: "pizza", category: "mouth", img: "extra-everything.webp" },
  { name: "Fire Of Confusion", traitValue: "blondehair", category: "head", img: "fire-of-confusion.webp" },
  { name: "Fireballs", traitValue: "orangegi", category: "clothes", img: "fireballs.webp" },
  { name: "Fomo Virus", traitValue: "mask", category: "mouth", img: "fomo-virus.webp" },
  { name: "Forest Fire", traitValue: "orangegi", category: "clothes", img: "forest-fire.webp" },
  { name: "Frozen Forever", traitValue: "bluearmor", category: "clothes", img: "frozen-forever.webp" },
  { name: "The Bark 10k Shiboshis", traitValue: "crosseyed", category: "eyes", img: "the-bark-of-10000-shiboshis.webp" },
  { name: "Fud Antidote Serum", traitValue: "mask", category: "mouth", img: "fud-antidote-serum.webp" },
  { name: "Futuristic Farmer", traitValue: "overalls", category: "clothes", img: "futuristic-farmer.webp" },
  { name: "Gill Mask", traitValue: "mask", category: "mouth", img: "gill-mask.webp" },
  { name: "Hack The Mainframe", traitValue: "cyborgeyes", category: "eyes", img: "hack-the-mainframe.webp" },
  { name: "Heatwave", traitValue: "blondehair", category: "head", img: "heatwave.webp" },
  { name: "Hedge Of Protection", traitValue: "halo", category: "head", img: "hedge-of-protection.webp" },
  { name: "Hells Guide", traitValue: "spirals", category: "eyes", img: "hells-guide.webp" },
  { name: "Herbalist", traitValue: "herb", category: "mouth", img: "herbalist.webp" },
  { name: "Heroes And Sheroes", traitValue: "mask", category: "mouth", img: "heroes-and-sheroes.webp" },
  { name: "High Noon Showdown", traitValue: "cowboyhat", category: "head", img: "high-noon-showdown.webp" },
  { name: "Hodl Mug", traitValue: "businesssuit", category: "clothes", img: "hodl-mug.webp" },
  { name: "Hytos Soldier", traitValue: "bluehair", category: "head", img: "hytos-soldier.webp" },
  { name: "I Am Ryosh3", traitValue: "normalmouth", category: "mouth", img: "i-am-ryosh3.webp" },
  { name: "I Am Ryoshi Too", traitValue: "normalmouth", category: "mouth", img: "i-am-ryoshi-too.webp" },
  { name: "Impassable Hodaven", traitValue: "wizardrobe", category: "clothes", img: "impassable-hodaven.webp" },
  { name: "Institutional Investor", traitValue: "tuxshirt", category: "clothes", img: "institutional-investor.webp" },
  { name: "Inu Shiba Inu", traitValue: "tuxshirt", category: "clothes", img: "inu-shiba-inu.webp" },
  { name: "Jerk Recipe", traitValue: "rasta", category: "head", img: "jerk-recipe.webp" },
  { name: "John Richmond Model", traitValue: "mohawk", category: "head", img: "john-richmond-model.webp" },
  { name: "Judgement", traitValue: "devilhorns", category: "head", img: "judgement.webp" },
  { name: "Junior Varsity Player", traitValue: "jersey", category: "clothes", img: "junior-varsity-player.webp" },
  { name: "Ryoshi", traitValue: "ryoshiclothes", category: "clothes", img: "ryoshi.webp" },
  { name: "Laser Fists", traitValue: "laservisor", category: "eyes", img: "laser-fists.webp" },
  { name: "Late April", traitValue: "clownhead", category: "head", img: "late-april.webp" },
  { name: "Leash Full Power", traitValue: "leash", category: "accessories", img: "leash-full-power.webp" },
  { name: "LFG", traitValue: "partypopper", category: "mouth", img: "lfg.webp" },
  { name: "Life Of The Party", traitValue: "partyhat", category: "head", img: "life-of-the-party.webp" },
  { name: "Lift Off", traitValue: "astroclothes", category: "clothes", img: "lift-off.webp" },
  { name: "Lightning Strike", traitValue: "nonehead", category: "head", img: "lightning-strike.webp" },
  { name: "Loan Forgiveness", traitValue: "university", category: "head", img: "loan-forgiveness.webp" },
  { name: "LOL", traitValue: "clownclothes", category: "clothes", img: "lol.webp" },
  { name: "Magic Trick", traitValue: "clownclothes", category: "clothes", img: "magic-trick.webp" },
  { name: "Magnetic Extraction", traitValue: "whistle", category: "mouth", img: "magnetic-extraction.webp" },
  { name: "Magnifying Heat Ray", traitValue: "monocle", category: "eyes", img: "magnifying-heat-ray.webp" },
  { name: "Make Love Not War", traitValue: "peacetank", category: "clothes", img: "make-love-not-war.webp" },
  { name: "Manicure", traitValue: "armyhead", category: "head", img: "manicure.webp" },
  { name: "Mariashi", traitValue: "sombrero", category: "head", img: "mariashi.webp" },
  { name: "Mechanical Bull", traitValue: "cowboyhat", category: "head", img: "mechanical-bull.webp" },
  { name: "Megawoof", traitValue: "growl", category: "mouth", img: "megawoof.webp" },
  { name: "Mercenaries", traitValue: "armyclothes", category: "clothes", img: "mercenaries.webp" },
  { name: "Mindreader", traitValue: "3dglasses", category: "eyes", img: "mindreader.webp" },
  { name: "More Than A Meme", traitValue: "memeshades", category: "eyes", img: "more-than-a-meme.webp" },
  { name: "Mosh Pit", traitValue: "mohawk", category: "head", img: "mosh-pit.webp" },
  { name: "Ms Shi Agi", traitValue: "glasses", category: "eyes", img: "ms-shi-agi.webp" },
  { name: "Mutant Pizza Protector", traitValue: "pizza", category: "mouth", img: "mutant-pizza-protector.webp" },
  { name: "Mutant Snowman", traitValue: "scarf", category: "clothes", img: "mutant-snowman.webp" },
  { name: "Last Shib Standing", traitValue: "lookforward", category: "eyes", img: "last-shib-standing.webp" },
  { name: "MVP", traitValue: "sportband", category: "head", img: "mvp.webp" },
  { name: "New Threads", traitValue: "tophat", category: "head", img: "new-threads.webp" },
  { name: "No More War", traitValue: "peacetank", category: "clothes", img: "no-more-war.webp" },
  { name: "Not My First Rodeo", traitValue: "cowboyhat", category: "head", img: "not-my-first-rodeo.webp" },
  { name: "Number Go Up", traitValue: "businesssuit", category: "clothes", img: "number-go-up.webp" },
  { name: "OB GYN Shib Doc", traitValue: "doctor", category: "clothes", img: "ob-gyn-shib-doc.webp" },
  { name: "OG Shib", traitValue: "beanie", category: "head", img: "og-shib.webp" },
  { name: "OL Shibster", traitValue: "cowboyclothes", category: "clothes", img: "olshibster.webp" },
  { name: "One Small Step For Shib", traitValue: "astroclothes", category: "clothes", img: "one-small-step-for-shib.webp" },
  { name: "Open Mic Night", traitValue: "pizza", category: "mouth", img: "open-mic-night.webp" },
  { name: "Our Last Hope", traitValue: "noneaccessories", category: "accessories", img: "our-last-hope.webp" },
  { name: "Pack Leader", traitValue: "armyclothes", category: "clothes", img: "pack-leader.webp" },
  { name: "Paperpaw Ku", traitValue: "dogtags", category: "accessories", img: "paperpaw-ku.webp" },
  { name: "Partnershibs", traitValue: "smirk", category: "mouth", img: "partnershibs.webp" },
  { name: "Party Pooper", traitValue: "partypopper", category: "mouth", img: "party-pooper.webp" },
  { name: "Party Til I Die", traitValue: "mohawk", category: "head", img: "party-til-i-die.webp" },
  { name: "Pawmap", traitValue: "doctor", category: "clothes", img: "pawmap.webp" },
  { name: "Peaceboshi", traitValue: "peacetank", category: "clothes", img: "peaceboshi.webp" },
  { name: "Perpetual Tickling", traitValue: "clownmouth", category: "mouth", img: "perpetual-tickling.webp" },
  { name: "Pet Bat", traitValue: "bathead", category: "head", img: "pet-bat.webp" },
  { name: "Plasma Cannon", traitValue: "armyclothes", category: "clothes", img: "plasma-cannon.webp" },
  { name: "Playoff Bribe", traitValue: "sportband", category: "head", img: "playoff-bribe.webp" },
  { name: "Plunder", traitValue: "piratepatch", category: "eyes", img: "plunder.webp" },
  { name: "Poison Preparation", traitValue: "tongueout", category: "mouth", img: "poison-preparation.webp" },
  { name: "Poncho Pattie", traitValue: "poncho", category: "clothes", img: "poncho-pattie.webp" },
  { name: "Power Of Decentralization", traitValue: "bone", category: "mouth", img: "power-of-decentralization.webp" },
  { name: "Princess Andromeda", traitValue: "crown", category: "head", img: "princess-andromeda.webp" },
  { name: "Printer Go Brrrr", traitValue: "tophat", category: "head", img: "printer-go-brrrr.webp" },
  { name: "Prophetess", traitValue: "rasta", category: "head", img: "prophetess.webp" },
  { name: "Protect The Princess", traitValue: "growl", category: "mouth", img: "protect-the-princess.webp" },
  { name: "Protective Companion", traitValue: "growl", category: "mouth", img: "protective-companion.webp" },
  { name: "Pure Light", traitValue: "halo", category: "head", img: "pure-light.webp" },
  { name: "Queens Ransom", traitValue: "piratepatch", category: "eyes", img: "queens-ransom.webp" },
  { name: "Rabid Beast", traitValue: "red", category: "eyes", img: "rabid-beast.webp" },
  { name: "Sedation", traitValue: "red", category: "eyes", img: "sedation.webp" },
  { name: "Reality Escaper", traitValue: "vr", category: "eyes", img: "reality-escaper.webp" },
  { name: "Red Alert Citadel", traitValue: "steelhead", category: "head", img: "red-alert-citadel.webp" },
  { name: "Red Carpet Affair", traitValue: "tuxshirt", category: "clothes", img: "red-carpet-affair.webp" },
  { name: "Rest In Peace", traitValue: "dogtags", category: "accessories", img: "rest-in-peace.webp" },
  { name: "Rock Out", traitValue: "rockervest", category: "clothes", img: "rock-out.webp" },
  { name: "Shib Ops Specialist", traitValue: "armyclothes", category: "clothes", img: "shib-ops-specialist.webp" },
  { name: "Shadowbat", traitValue: "batclothes", category: "clothes", img: "shadowbat.webp" },
  { name: "Shadowcat Antivenom", traitValue: "wizardrobe", category: "clothes", img: "shadowcat-antivenom.webp" },
  { name: "Shadowcat Ghoul", traitValue: "noneclothes", category: "clothes", img: "shadowcat-ghoul.webp" },
  { name: "Shadowcat Jumper", traitValue: "ryoshiclothes", category: "clothes", img: "shadowcat-jumper.webp" },
  { name: "Shadowcat Princess", traitValue: "devilhorns", category: "head", img: "shadowcat-princess.webp" },
  { name: "Shadowcats Pet Mouse", traitValue: "clownmouth", category: "mouth", img: "shadowcats-pet-mouse.webp" },
  { name: "She Is Ryoshi", traitValue: "ryoshiclothes", category: "clothes", img: "she-is-ryoshi.webp" },
  { name: "Shib Army Recruit", traitValue: "armyhead", category: "head", img: "shib-army-recruit.webp" },
  { name: "Shib Chancla", traitValue: "poncho", category: "clothes", img: "shib-chancla.webp" },
  { name: "Shib Designer Shades", traitValue: "memeshades", category: "eyes", img: "shib-designer-shades.webp" },
  { name: "Shib Maxi", traitValue: "lasereyes", category: "eyes", img: "shib-maxi.webp" },
  { name: "Shib Metaverse Stroll", traitValue: "vr", category: "eyes", img: "shib-metaverse-stroll.webp" },
  { name: "Shib Pinata", traitValue: "poncho", category: "clothes", img: "shib-pinata.webp" },
  { name: "Shib Quinceanera", traitValue: "sombrero", category: "head", img: "shib-quinceanera.webp" },
  { name: "Shib Samurai Shogun", traitValue: "bluearmor", category: "clothes", img: "shib-samurai-shogun.webp" },
  { name: "Shib Scammer", traitValue: "nofud", category: "clothes", img: "shib-scammer.webp" },
  { name: "Shib Squadron", traitValue: "steelhead", category: "head", img: "shib-squadron.webp" },
  { name: "Shib Submarine", traitValue: "captainshat", category: "head", img: "shib-submarine.webp" },
  { name: "Shib Swashbuckler", traitValue: "piratepatch", category: "eyes", img: "shib-swashbuckler.webp" },
  { name: "Shiba Moon Hopeful", traitValue: "glasses", category: "eyes", img: "shiba-moon-hopeful.webp" },
  { name: "Shibaclops", traitValue: "laservisor", category: "eyes", img: "shibaclops.webp" },
  { name: "Shibarium Payments", traitValue: "ryoshiclothes", category: "clothes", img: "shibarium-payments.webp" },
  { name: "LC The Ancient Of Shib", traitValue: "nofud", category: "clothes", img: "lc-the-ancient-of-shib.webp" },
  { name: "Shibluminati", traitValue: "tophat", category: "head", img: "shibluminati.webp" },
  { name: "Shiborg", traitValue: "cyborgeyes", category: "eyes", img: "shiborg.webp" },
  { name: "Shibosian Volcano", traitValue: "pipe", category: "mouth", img: "shibosian-volcano.webp" },
  { name: "Shibtopia Clergy", traitValue: "vr", category: "eyes", img: "shibtopia-clergy.webp" },
  { name: "Shots", traitValue: "partyhat", category: "head", img: "shots.webp" },
  { name: "Shys Messenger Bag", traitValue: "noneaccessories", category: "accessories", img: "shys-messenger-bag.webp" },
  { name: "Sentience", traitValue: "cyborghead", category: "head", img: "sentience.webp" },
  { name: "Ryoshi's Katanas", traitValue: "noneaccessories", category: "accessories", img: "ryoshis-katanas.webp" },
  { name: "Siesta Sindy", traitValue: "sombrero", category: "head", img: "siesta-sindy.webp" },
  { name: "Silenced Pistol", traitValue: "tuxshirt", category: "clothes", img: "silenced-pistol.webp" },
  { name: "Sinking Captain", traitValue: "captainshat", category: "head", img: "sinking-captain.webp" },
  { name: "Skeleton Crew", traitValue: "piratehead", category: "head", img: "skeleton-crew.webp" },
  { name: "Snowman", traitValue: "scarf", category: "clothes", img: "snowman.webp" },
  { name: "Solar Flare", traitValue: "orangegi", category: "clothes", img: "solar-flare.webp" },
  { name: "Sold Early", traitValue: "clownhead", category: "head", img: "sold-early.webp" },
  { name: "Sold Out Shib", traitValue: "spirals", category: "eyes", img: "sold-out-shib.webp" },
  { name: "Golden Ser", traitValue: "halo", category: "head", img: "golden-ser.webp" },
  { name: "Solder Ships", traitValue: "lasereyes", category: "eyes", img: "solder-ships.webp" },
  { name: "Shib Ship One", traitValue: "classiceyes", category: "eyes", img: "shib-ship-one.webp" },
  { name: "Sole Survivor", traitValue: "steelclothes", category: "clothes", img: "sole-survivor.webp" },
  { name: "Soon", traitValue: "devclothes", category: "clothes", img: "soon.webp" },
  { name: "Spirit Realm Invaders", traitValue: "halo", category: "head", img: "spirit-realm-invaders.webp" },
  { name: "SS Virgil Crew Member", traitValue: "sailor", category: "clothes", img: "ss-virgil-crew-member.webp" },
  { name: "Stage Diver", traitValue: "rockervest", category: "clothes", img: "stage-diver.webp" },
  { name: "Stainless Sam", traitValue: "steelclothes", category: "clothes", img: "stainless-sam.webp" },
  { name: "Stick Up", traitValue: "cowboyclothes", category: "clothes", img: "stick-up.webp" },
  { name: "Sticky Fur", traitValue: "bubblegum", category: "mouth", img: "sticky-fur.webp" },
  { name: "Sticky Icky", traitValue: "bubblegum", category: "mouth", img: "sticky-icky.webp" },
  { name: "Struck Oil", traitValue: "cowboyclothes", category: "clothes", img: "struck-oil.webp" },
  { name: "Student Loans", traitValue: "university", category: "head", img: "student-loans.webp" },
  { name: "Suftstick", traitValue: "rasta", category: "head", img: "suftstick.webp" },
  { name: "Summon The Army", traitValue: "captainshat", category: "head", img: "summon-the-army.webp" },
  { name: "Sunlight Immune Ian", traitValue: "batclothes", category: "clothes", img: "sunlight-immune-ian.webp" },
  { name: "T-Bone Collector", traitValue: "bone", category: "mouth", img: "t-bone-collector.webp" },
  { name: "Taco Tuesday", traitValue: "poncho", category: "clothes", img: "taco-tuesday.webp" },
  { name: "Tattoo Newby", traitValue: "mohawk", category: "head", img: "tattoo-newby.webp" },
  { name: "Tattooed Toni", traitValue: "rockermakeup", category: "eyes", img: "tattooed-toni.webp" },
  { name: "Teresian Chef", traitValue: "partyhat", category: "head", img: "teresian-chef.webp" },
  { name: "Teresian Party", traitValue: "partyhat", category: "head", img: "teresian-party.webp" },
  { name: "Tersian Masseuse", traitValue: "flames", category: "mouth", img: "tersian-masseuse.webp" },
  { name: "Tethered Shib", traitValue: "normalmouth", category: "mouth", img: "tethered-shib.webp" },
  { name: "The Boss", traitValue: "piratehead", category: "head", img: "the-boss.webp" },
  { name: "The Bubble Blaster", traitValue: "pipe", category: "mouth", img: "the-bubble-blaster.webp" },
  { name: "The Candy Shop", traitValue: "lollipop", category: "mouth", img: "the-candy-shop.webp" },
  { name: "The Crimson Pirate", traitValue: "lasereyes", category: "eyes", img: "the-crimson-pirate.webp" },
  { name: "The Divine Protector", traitValue: "wizardrobe", category: "clothes", img: "the-divine-protector.webp" },
  { name: "The Fire Breather", traitValue: "blondehair", category: "head", img: "the-fire-breather.webp" },
  { name: "The Harvest", traitValue: "overalls", category: "clothes", img: "the-harvest.webp" },
  { name: "The Janky Ref", traitValue: "whistle", category: "mouth", img: "the-janky-ref.webp" },
  { name: "The Jokes On You", traitValue: "clownhead", category: "head", img: "the-jokes-on-you.webp" },
  { name: "The Leash", traitValue: "leash", category: "accessories", img: "the-leash.webp" },
  { name: "The Librarian", traitValue: "monocle", category: "eyes", img: "the-librarian.webp" },
  { name: "The Magicians Table", traitValue: "wizardhat", category: "head", img: "the-magicians-table.webp" },
  { name: "The Shibbuckler", traitValue: "piratehead", category: "head", img: "the-shibbuckler.webp" },
  { name: "The Shiboshi Outlaw", traitValue: "cowboyclothes", category: "clothes", img: "the-shiboshi-outlaw.webp" },
  { name: "The Soul Stare", traitValue: "ryoshihead", category: "head", img: "the-soul-stare.webp" },
  { name: "The Stylish One", traitValue: "earrings", category: "accessories", img: "the-stylish-one.webp" },
  { name: "Top Kek", traitValue: "clownclothes", category: "clothes", img: "top-kek.webp" },
  { name: "Torn ACL", traitValue: "jersey", category: "clothes", img: "torn-acl.webp" },
  { name: "Torpedoes Away", traitValue: "sailor", category: "clothes", img: "torpedoes-away.webp" },
  { name: "Guardian Of The Throne", traitValue: "blackmask", category: "eyes", img: "guardian-of-the-throne.webp" },
  { name: "Train Robber", traitValue: "blackmask", category: "eyes", img: "train-robber.webp" },
  { name: "Transformation", traitValue: "clownhead", category: "head", img: "transformation.webp" },
  { name: "Trick Or Treat", traitValue: "lollipop", category: "mouth", img: "trick-or-treat.webp" },
  { name: "True Form Mechanic", traitValue: "bathead", category: "head", img: "true-form-mechanic.webp" },
  { name: "Ultramage", traitValue: "wizardhat", category: "accessories", img: "ultramage.webp" },
  { name: "Un-Caped Crusaders", traitValue: "doctor", category: "clothes", img: "un-caped-crusaders.webp" },
  { name: "Valedictorian", traitValue: "university", category: "head", img: "valedictorian.webp" },
  { name: "Vaquero Shib", traitValue: "sombrero", category: "head", img: "vaquero-shib.webp" },
  { name: "Varsity Star", traitValue: "jersey", category: "clothes", img: "varsity-star.webp" },
  { name: "VR Arcade Worker", traitValue: "vr", category: "eyes", img: "vr-arcade-worker.webp" },
  { name: "Wedding Date", traitValue: "wink", category: "eyes", img: "wedding-date.webp" },
  { name: "Welly's Fire Special", traitValue: "bone", category: "mouth", img: "wellys-fire-special.webp" },
  { name: "Wen", traitValue: "devclothes", category: "clothes", img: "wen.webp" },
  { name: "Send It", traitValue: "devclothes", category: "clothes", img: "send-it.webp" },
  { name: "Whale Pod", traitValue: "sailor", category: "clothes", img: "whale-pod.webp" },
  { name: "Wilderness Warrior", traitValue: "herb", category: "mouth", img: "wilderness-warrior.webp" },
  { name: "Wise Investor", traitValue: "businesssuit", category: "clothes", img: "wise-investor.webp" },
  { name: "Woof Ryders", traitValue: "rockervest", category: "clothes", img: "woof-ryders.webp" },
  { name: "Woolley Eyes", traitValue: "beanie", category: "head", img: "woolley-eyes.webp" },
  { name: "World Tour", traitValue: "rockermakeup", category: "eyes", img: "world-tour.webp" },
  { name: "X Marks The Spot", traitValue: "piratehead", category: "head", img: "x-marks-the-spot.webp" },
  { name: "Xray Glasses", traitValue: "3dglasses", category: "eyes", img: "xray-glasses.webp" },
  { name: "Y The Agent", traitValue: "scarf", category: "clothes", img: "y-the-agent.webp" },
  { name: "Yek Of Ancient Lore", traitValue: "orangegi", category: "clothes", img: "yek-of-ancient-lore.webp" },
  { name: "Yek Of Shadowcat Ghoul", traitValue: "cyborghead", category: "head", img: "yek-of-shadowcat-ghoul.webp" },
  { name: "Zoom Out", traitValue: "lookforward", category: "eyes", img: "zoom-out.webp" },
  { name: "Target Acquired", traitValue: "lookforward", category: "eyes", img: "target-acquired.webp" },
  { name: "Paws", traitValue: "chewjitsu", category: "discipline", img: "paws.webp" },
  { name: "Cutterbutter", traitValue: "chewjitsu", category: "discipline", img: "cutterbutter.webp" },
  { name: "Whisky", traitValue: "chewjitsu", category: "discipline", img: "whisky.webp" },
  { name: "Frenzied Pup", traitValue: "chewjitsu", category: "discipline", img: "frenzied-pup.webp" },
  { name: "Mumma Floof", traitValue: "chewjitsu", category: "discipline", img: "mumma-floof.webp" },
  { name: "Training Dummy", traitValue: "chewjitsu", category: "discipline", img: "training-dummy.webp" },
  { name: "Chewjitsu Fanatic", traitValue: "chewjitsu", category: "discipline", img: "chewjitsu-fanatic.webp" },
  { name: "Hiro", traitValue: "chewjitsu", category: "discipline", img: "hiro.webp" },
  { name: "Luna The Loyalist", traitValue: "chewjitsu", category: "discipline", img: "luna-the-loyalist.webp" },
  { name: "Rafi Hard Strike", traitValue: "chewjitsu", category: "discipline", img: "rafi-hard-strike.webp" },
  { name: "Historian Hoots", traitValue: "chewjitsu", category: "discipline", img: "historian-hoots.webp" },
  { name: "Swiftpaw Showoff", traitValue: "chewjitsu", category: "discipline", img: "swiftpaw-showoff.webp" },
  { name: "Benji Trickwhip", traitValue: "chewjitsu", category: "discipline", img: "benji-trickwhip.webp" },
  { name: "Sensei Borku-San", traitValue: "chewjitsu", category: "discipline", img: "sensei-borku-san.webp" },
  { name: "Astrid The Unbreakable", traitValue: "chewjitsu", category: "discipline", img: "astrid-the-unbreakable.webp" },
  { name: "Squeakers Lifoot", traitValue: "chewjitsu", category: "discipline", img: "squeakers-lifoot.webp" },
  { name: "Iron Fur Brawler", traitValue: "chewjitsu", category: "discipline", img: "iron-fur-brawler.webp" },
  { name: "Pango", traitValue: "chewjitsu", category: "discipline", img: "pango.webp" },
  { name: "Cone of Shame", traitValue: "chewjitsu", category: "discipline", img: "cone-of-shame.webp" },
  { name: "Second Wind", traitValue: "chewjitsu", category: "discipline", img: "second-wind.webp" },
  { name: "Forgotten Artifacts", traitValue: "chewjitsu", category: "discipline", img: "forgotten-artifacts.webp" },
  { name: "Aimless Strikes", traitValue: "chewjitsu", category: "discipline", img: "aimless-strikes.webp" },
  { name: "Impart Wisdom", traitValue: "chewjitsu", category: "discipline", img: "impart-wisdom.webp" },
  { name: "Defensive Stance", traitValue: "chewjitsu", category: "discipline", img: "defensive-stance.webp" },
  { name: "Paw of Destruction", traitValue: "chewjitsu", category: "discipline", img: "paw-of-destruction.webp" },
  { name: "Trusty Katana", traitValue: "chewjitsu", category: "discipline", img: "trusty-katana.webp" },
  { name: "Pawprint Sai", traitValue: "chewjitsu", category: "discipline", img: "pawprint-sai.webp" },
  { name: "Bone Nunchucks", traitValue: "chewjitsu", category: "discipline", img: "bone-nunchucks.webp" },
  { name: "Relentless Naginata", traitValue: "chewjitsu", category: "discipline", img: "relentless-naginata.webp" },
  { name: "Toothy Kama", traitValue: "chewjitsu", category: "discipline", img: "toothy-kama.webp" },
  { name: "Lightfoot Swinger", traitValue: "taekwondoje", category: "discipline", img: "lightfoot-swinger.webp" },
  { name: "Steadfast Halter", traitValue: "taekwondoje", category: "discipline", img: "steadfast-halter.webp" },
  { name: "Two-Toed Valiant", traitValue: "taekwondoje", category: "discipline", img: "two-toed-valiant.webp" },
  { name: "Sansa Mana Fist", traitValue: "taekwondoje", category: "discipline", img: "sansa-mana-fist.webp" },
  { name: "Thrill Pouncer", traitValue: "taekwondoje", category: "discipline", img: "thrill-pouncer.webp" },
  { name: "Butterfly Brave", traitValue: "taekwondoje", category: "discipline", img: "butterfly-brave.webp" },
  { name: "Long-Snout Chomper", traitValue: "taekwondoje", category: "discipline", img: "long-snout-chomper.webp" },
  { name: "Makto Horde Bearer", traitValue: "taekwondoje", category: "discipline", img: "makto-horde-bearer.webp" },
  { name: "Pusuke Ageless Companion", traitValue: "taekwondoje", category: "discipline", img: "pusuke-ageless-companion.webp" },
  { name: "Snowball Charge Loft", traitValue: "taekwondoje", category: "discipline", img: "snowball-charge-loft.webp" },
  { name: "Treasured Scholar", traitValue: "taekwondoje", category: "discipline", img: "treasured-scholar.webp" },
  { name: "Cross Guarder", traitValue: "taekwondoje", category: "discipline", img: "cross-guarder.webp" },
  { name: "Senna Many Feather", traitValue: "taekwondoje", category: "discipline", img: "senna-many-feather.webp" },
  { name: "Jealous Gull", traitValue: "taekwondoje", category: "discipline", img: "jealous-gull.webp" },
  { name: "Lightfoot Master", traitValue: "taekwondoje", category: "discipline", img: "lightfoot-master.webp" },
  { name: "Arya Mana Fort", traitValue: "taekwondoje", category: "discipline", img: "arya-mana-fort.webp" },
  { name: "Chester the Undeterred", traitValue: "taekwondoje", category: "discipline", img: "chester-the-undeterred.webp" },
  { name: "Doppleganger Upper", traitValue: "taekwondoje", category: "discipline", img: "doppleganger-upper.webp" },
  { name: "Fleetfoot Charger", traitValue: "taekwondoje", category: "discipline", img: "fleetfoot-charger.webp" },
  { name: "Grand Sentry Gelert", traitValue: "taekwondoje", category: "discipline", img: "grand-sentry-gelert.webp" },
  { name: "Bull Wark", traitValue: "taekwondoje", category: "discipline", img: "bull-wark.webp" },
  { name: "Brightest Flame", traitValue: "taekwondoje", category: "discipline", img: "brightest-flame.webp" },
  { name: "Booky Buffalo", traitValue: "taekwondoje", category: "discipline", img: "booky-buffalo.webp" },
  { name: "Stand Guard", traitValue: "taekwondoje", category: "discipline", img: "stand-guard.webp" },
  { name: "Meditate", traitValue: "taekwondoje", category: "discipline", img: "meditate.webp" },
  { name: "Overcharge", traitValue: "taekwondoje", category: "discipline", img: "overcharge.webp" },
  { name: "Strike Support", traitValue: "taekwondoje", category: "discipline", img: "strike-support.webp" },
  { name: "Dogjo Armory", traitValue: "taekwondoje", category: "discipline", img: "dogjo-armory.webp" },
  { name: "Magic Mirror", traitValue: "taekwondoje", category: "discipline", img: "magic-mirror.webp" },
  { name: "The High Ground", traitValue: "taekwondoje", category: "discipline", img: "the-high-ground.webp" },
  { name: "Young Disciple", traitValue: "ryo chi", category: "discipline", img: "young-disciple.webp" },
  { name: "Bricc", traitValue: "ryo chi", category: "discipline", img: "bricc.webp" },
  { name: "Southpaw Protector", traitValue: "ryo chi", category: "discipline", img: "southpaw-protector.webp" },
  { name: "Voodoo Runner", traitValue: "ryo chi", category: "discipline", img: "voodoo-runner.webp" },
  { name: "Kingmaker", traitValue: "ryo chi", category: "discipline", img: "kingmaker.webp" },
  { name: "Resilient Rowan", traitValue: "ryo chi", category: "discipline", img: "resilient-rowan.webp" },
  { name: "Timid Merchant", traitValue: "ryo chi", category: "discipline", img: "timid-merchant.webp" },
  { name: "Cheer-Chuck", traitValue: "ryo chi", category: "discipline", img: "cheer-chuck.webp" },
  { name: "Lana Longreach", traitValue: "ryo chi", category: "discipline", img: "lana-longreach.webp" },
  { name: "Glory Armorer", traitValue: "ryo chi", category: "discipline", img: "glory-armorer.webp" },
  { name: "Merrett Eversight", traitValue: "ryo chi", category: "discipline", img: "merrett-eversight.webp" },
  { name: "Taskmaster Paido", traitValue: "ryo chi", category: "discipline", img: "taskmaster-paido.webp" },
  { name: "Reginald Sleevy", traitValue: "ryo chi", category: "discipline", img: "reginald-sleevy.webp" },
  { name: "Irebound Mystic", traitValue: "ryo chi", category: "discipline", img: "irebound-mystic.webp" },
  { name: "Tuftier Monk", traitValue: "ryo chi", category: "discipline", img: "tuftier-monk.webp" },
  { name: "Wing Mill", traitValue: "ryo chi", category: "discipline", img: "wing-mill.webp" },
  { name: "Jade Baron Amadeus", traitValue: "ryo chi", category: "discipline", img: "jade-baron-amadeus.webp" },
  { name: "Mina the Untouchable", traitValue: "ryo chi", category: "discipline", img: "mina-the-untouchable.webp" },
  { name: "Shortclaw Giant", traitValue: "ryo chi", category: "discipline", img: "shortclaw-giant.webp" },
  { name: "Shield Brother", traitValue: "ryo chi", category: "discipline", img: "shield-brother.webp" },
  { name: "Storm Preparations", traitValue: "ryo chi", category: "discipline", img: "storm-preparations.webp" },
  { name: "Fortitude Tutoring", traitValue: "ryo chi", category: "discipline", img: "fortitude-tutoring.webp" },
  { name: "Ancestral Blessing", traitValue: "ryo chi", category: "discipline", img: "ancestral-blessing.webp" },
  { name: "Healthy Coat", traitValue: "ryo chi", category: "discipline", img: "healthy-coat.webp" },
  { name: "Unwavering Protection", traitValue: "ryo chi", category: "discipline", img: "unwavering-protection.webp" },
  { name: "Divine Resolution", traitValue: "ryo chi", category: "discipline", img: "divine-resolution.webp" },
  { name: "Sturdy Pole", traitValue: "ryo chi", category: "discipline", img: "sturdy-pole.webp" },
  { name: "Barbed Spear", traitValue: "ryo chi", category: "discipline", img: "barbed-spear.webp" },
  { name: "Ceremonial Sword", traitValue: "ryo chi", category: "discipline", img: "ceremonial-sword.webp" },
  { name: "Cogwork Sabre", traitValue: "ryo chi", category: "discipline", img: "cogwork-sabre.webp" },
  { name: "Gruff Charger", traitValue: "bite thai", category: "discipline", img: "gruff-charger.webp" },
  { name: "Old Chomper", traitValue: "bite thai", category: "discipline", img: "old-chomper.webp" },
  { name: "Scrapp", traitValue: "bite thai", category: "discipline", img: "scrapp.webp" },
  { name: "Feral Tackler", traitValue: "bite thai", category: "discipline", img: "feral-tackler.webp" },
  { name: "Fang Tutor", traitValue: "bite thai", category: "discipline", img: "fang-tutor.webp" },
  { name: "Arcane Hellion", traitValue: "bite thai", category: "discipline", img: "arcane-hellion.webp" },
  { name: "Jordi Stonefist", traitValue: "bite thai", category: "discipline", img: "jordi-stonefist.webp" },
  { name: "Gentle Giant", traitValue: "bite thai", category: "discipline", img: "gentle-giant.webp" },
  { name: "Helpful Heckler", traitValue: "bite thai", category: "discipline", img: "helpful-heckler.webp" },
  { name: "Destroyer Driessen", traitValue: "bite thai", category: "discipline", img: "destroyer-driessen.webp" },
  { name: "Knuckle Brawler", traitValue: "bite thai", category: "discipline", img: "knuckle-brawler.webp" },
  { name: "Hardclaw Mystic", traitValue: "bite thai", category: "discipline", img: "hardclaw-mystic.webp" },
  { name: "Crimson Champion", traitValue: "bite thai", category: "discipline", img: "crimson-champion.webp" },
  { name: "Sawtooth", traitValue: "bite thai", category: "discipline", img: "sawtooth.webp" },
  { name: "Lady Wildclaw", traitValue: "bite thai", category: "discipline", img: "lady-wildclaw.webp" },
  { name: "King Finder Togo", traitValue: "bite thai", category: "discipline", img: "king-finder-togo.webp" },
  { name: "Crested Strategist", traitValue: "bite thai", category: "discipline", img: "crested-strategist.webp" },
  { name: "Herald of Tremors", traitValue: "bite thai", category: "discipline", img: "herald-of-tremors.webp" },
  { name: "Unstoppable Horde", traitValue: "bite thai", category: "discipline", img: "unstoppable-horde.webp" },
  { name: "Cerberus Whistle-Threat", traitValue: "bite thai", category: "discipline", img: "cerberus-whistle-threat.webp" },
  { name: "Big Sis", traitValue: "bite thai", category: "discipline", img: "big-sis.webp" },
  { name: "Wandering Mammoth", traitValue: "bite thai", category: "discipline", img: "wandering-mammoth.webp" },
  { name: "Glass Claws", traitValue: "bite thai", category: "discipline", img: "glass-claws.webp" },
  { name: "High Tackle", traitValue: "bite thai", category: "discipline", img: "high-tackle.webp" },
  { name: "Ramming Strike", traitValue: "bite thai", category: "discipline", img: "ramming-strike.webp" },
  { name: "Scare Off", traitValue: "bite thai", category: "discipline", img: "scare-off.webp" },
  { name: "Talon Typhoon", traitValue: "bite thai", category: "discipline", img: "talon-typhoon.webp" },
  { name: "Breakneck Pace", traitValue: "bite thai", category: "discipline", img: "breakneck-pace.webp" },
  { name: "Primeval Power", traitValue: "bite thai", category: "discipline", img: "primeval-power.webp" },
  { name: "Jurassic Bark", traitValue: "bite thai", category: "discipline", img: "jurassic-bark.webp" },
  { name: "Grasshoppa", traitValue: "woof chun", category: "discipline", img: "grasshoppa.webp" },
  { name: "Mavel", traitValue: "woof chun", category: "discipline", img: "mavel.webp" },
  { name: "Eager Sidekick", traitValue: "woof chun", category: "discipline", img: "eager-sidekick.webp" },
  { name: "Softpaw Bolter", traitValue: "woof chun", category: "discipline", img: "softpaw-bolter.webp" },
  { name: "Momiji", traitValue: "woof chun", category: "discipline", img: "momiji.webp" },
  { name: "Pupper Trainer", traitValue: "woof chun", category: "discipline", img: "pupper-trainer.webp" },
  { name: "Payback Pete", traitValue: "woof chun", category: "discipline", img: "payback-pete.webp" },
  { name: "Toothy Heckler", traitValue: "woof chun", category: "discipline", img: "toothy-heckler.webp" },
  { name: "Glory Glutton", traitValue: "woof chun", category: "discipline", img: "glory-glutton.webp" },
  { name: "Heavy Slugger", traitValue: "woof chun", category: "discipline", img: "heavy-slugger.webp" },
  { name: "Shell Bard", traitValue: "woof chun", category: "discipline", img: "shell-bard.webp" },
  { name: "Coco, The Charger", traitValue: "woof chun", category: "discipline", img: "coco-the-charger.webp" },
  { name: "Supply Chief", traitValue: "woof chun", category: "discipline", img: "supply-chief.webp" },
  { name: "Whitetail Brawler", traitValue: "woof chun", category: "discipline", img: "whitetail-brawler.webp" },
  { name: "Bandana Bretta", traitValue: "woof chun", category: "discipline", img: "bandana-bretta.webp" },
  { name: "Flag Bear-er", traitValue: "woof chun", category: "discipline", img: "flag-bear-er.webp" },
  { name: "Fowl Hardy", traitValue: "woof chun", category: "discipline", img: "fowl-hardy.webp" },
  { name: "Multiplying Menace", traitValue: "woof chun", category: "discipline", img: "multiplying-menace.webp" },
  { name: "Hornfel, The Tireless", traitValue: "woof chun", category: "discipline", img: "hornfel-the-tireless.webp" },
  { name: "Copper, Bane-Blade", traitValue: "woof chun", category: "discipline", img: "copper-bane-blade.webp" },
  { name: "Prickly Present", traitValue: "woof chun", category: "discipline", img: "prickly-present.webp" },
  { name: "Bouncing Bolt", traitValue: "woof chun", category: "discipline", img: "bouncing-bolt.webp" },
  { name: "Primal Howl", traitValue: "woof chun", category: "discipline", img: "primal-howl.webp" },
  { name: "Pinch & Punch", traitValue: "woof chun", category: "discipline", img: "pinch-and-punch.webp" },
  { name: "Wargghghh!!", traitValue: "woof chun", category: "discipline", img: "wargghghh.webp" },
  { name: "Tall Grass Terrors", traitValue: "woof chun", category: "discipline", img: "tall-grass-terrors.webp" },
  { name: "Bamboo Long Pole", traitValue: "woof chun", category: "discipline", img: "bamboo-long-pole.webp" },
  { name: "Butterfly Swords", traitValue: "woof chun", category: "discipline", img: "butterfly-swords.webp" },
  { name: "Concrete Pillar", traitValue: "woof chun", category: "discipline", img: "concrete-pillar.webp" },
  { name: "Quadruple Swords", traitValue: "woof chun", category: "discipline", img: "quadruple-swords.webp" },
  { name: "Long-Claw Runner", traitValue: "shyjitsu", category: "discipline", img: "long-claw-runner.webp" },
  { name: "Armed Pacifier", traitValue: "shyjitsu", category: "discipline", img: "armed-pacifier.webp" },
  { name: "Fiesty Fletcher", traitValue: "shyjitsu", category: "discipline", img: "fiesty-fletcher.webp" },
  { name: "Double Claw", traitValue: "shyjitsu", category: "discipline", img: "double-claw.webp" },
  { name: "Shadow Patches", traitValue: "shyjitsu", category: "discipline", img: "shadow-patches.webp" },
  { name: "Distraction Prodigy", traitValue: "shyjitsu", category: "discipline", img: "distraction-prodigy.webp" },
  { name: "Undercover Pupper", traitValue: "shyjitsu", category: "discipline", img: "undercover-pupper.webp" },
  { name: "Mr. Jekyll", traitValue: "shyjitsu", category: "discipline", img: "mr-jekyll.webp" },
  { name: "Meditative Master", traitValue: "shyjitsu", category: "discipline", img: "meditative-master.webp" },
  { name: "Maya, Hook-Knife", traitValue: "shyjitsu", category: "discipline", img: "maya-hook-knife.webp" },
  { name: "Unsuspicious Smuggler", traitValue: "shyjitsu", category: "discipline", img: "unsuspicious-smuggler.webp" },
  { name: "Shadow Smith", traitValue: "shyjitsu", category: "discipline", img: "shadow-smith.webp" },
  { name: "Boaris Quickslice", traitValue: "shyjitsu", category: "discipline", img: "boaris-quickslice.webp" },
  { name: "Hidden Boulder", traitValue: "shyjitsu", category: "discipline", img: "hidden-boulder.webp" },
  { name: "Sensei SNR", traitValue: "shyjitsu", category: "discipline", img: "sensei-snr.webp" },
  { name: "Paralytic Pariah", traitValue: "shyjitsu", category: "discipline", img: "paralytic-pariah.webp" },
  { name: "Clover & Carver", traitValue: "shyjitsu", category: "discipline", img: "clover-and-carver.webp" },
  { name: "Nyght", traitValue: "shyjitsu", category: "discipline", img: "nyght.webp" },
  { name: "Famed Daimyo", traitValue: "shyjitsu", category: "discipline", img: "famed-daimyo.webp" },
  { name: "Arcane Bladebreaker", traitValue: "shyjitsu", category: "discipline", img: "arcane-bladebreaker.webp" },
  { name: "Underhanded Dagger", traitValue: "shyjitsu", category: "discipline", img: "underhanded-dagger.webp" },
  { name: "Swoop N' Loot", traitValue: "shyjitsu", category: "discipline", img: "swoop-n-loot.webp" },
  { name: "Get In Position", traitValue: "shyjitsu", category: "discipline", img: "get-in-position.webp" },
  { name: "Smoke Screen", traitValue: "shyjitsu", category: "discipline", img: "smoke-screen.webp" },
  { name: "Hidden In Plain Sight", traitValue: "shyjitsu", category: "discipline", img: "hidden-in-plain-sight.webp" },
  { name: "Gunpowder Mischief", traitValue: "shyjitsu", category: "discipline", img: "gunpowder-mischief.webp" },
  { name: "Sharpened Kunai", traitValue: "shyjitsu", category: "discipline", img: "sharpened-kunai.webp" },
  { name: "Frozen Shuriken", traitValue: "shyjitsu", category: "discipline", img: "frozen-shuriken.webp" },
  { name: "Keen Kusarigama", traitValue: "shyjitsu", category: "discipline", img: "keen-kusarigama.webp" },
  { name: "Boundless Nagamaki", traitValue: "shyjitsu", category: "discipline", img: "boundless-nagamaki.webp" },
  { name: "System Shock", traitValue: "black", category: "fur", img: "system-shock.webp" },
  { name: "Small Jolt", traitValue: "black", category: "fur", img: "small-jolt.webp" }
];

export const generateCardPool = (count: number = 502): CardData[] => {
  return RAW_CARDS.map((card, index) => ({
    id: `card-${index + 1}`,
    name: card.name,
    category: card.category as any,
    traitValue: card.traitValue,
    imageUrl: `/${card.img}`, 
  }));
};
